### PR TITLE
Fixing gateway does not send all retained messages

### PR DESCRIPTION
**Pull request by a1lu**
If a client subscribes topics that are retained, the gateway did not forward all messages at once if they used QoS=0.

I created the PR and hope that the pipeline runs the tests, unfortunately I can't run them currently.

Fixes https://github.com/commschamp/cc.mqttsn.libs/issues/12

### CODE REVIEW

**Comment by arobenko** [comment]
Looks like there are some [unittests failures](https://ci.appveyor.com/project/arobenko/cc-mqttsn-libs/builds/47471067). There is probably the problem with the unittest itself, but if you can it's better to be analyzed before I click the merge button.

**Comment by arobenko** [comment]
You can also add "-V" parameter to the ctest invocation inside the ".appveyor.yml". It will print the details what test fails. Strangely I don't see the github actions building and testing the pull request.

**Comment by a1lu** [comment]
I could not test locally because my cmake could not find `cc_cxxtest_add_test`. Could you tell me what I need to include / set to have this function?

**Comment by a1lu** [comment]
The following test fails:
```
3: In SessionTest::test16:
3: c:\projects\cc_mqttsn\build.x64.debug.msvc14\gateway\test\..\..\..\gateway\test\Session.th:1320: Error: Assertion failed: state.m_sentToClient.empty()
```

**Comment by arobenko** [comment]
The `cc_cxxtest_add_test` is provided by the [comms library](https://github.com/commschamp/comms/blob/master/cmake/CC_CxxtestFuncs.cmake#L139). Included [here](https://github.com/commschamp/cc.mqttsn.libs/blob/master/CMakeLists.txt#L74). The *LibComms_DIR* variable is expected to contain the directory path where "LibCommsConfig.cmake" is located (set by the `find_package(LibComms REQUIRED)`)

**Comment by arobenko** [comment]
You can also use [script/full_debug_build_gcc.sh](https://github.com/commschamp/cc.mqttsn.libs/blob/master/script/full_debug_build_gcc.sh) to perform a full build with unittests.

**Comment by arobenko** [comment]
Looks like the problem is a bit deeper than expected. After you build the unittests (from develop branch) you can run the problematic one in verbose mode by:
```
cd <build_dir>
./gateway/test/cc.mqttsn.gateway.SessionTest -v SessionTest test16
Running cxxtest tests (1 test)
In SessionTest::test16:
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:371: Trace: "(CLIENT) --> CONNECT"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:936: Trace: (BROKER) <-- CONNECT
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:381: Trace: "(BROKER) --> CONNACK"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:441: Trace: (CLIENT) <-- CONNACK
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:1314: Trace: "[Connected client]: client"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:371: Trace: "(CLIENT) --> DISCONNECT"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:513: Trace: (CLIENT) <-- DISCONNECT
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:1028: Trace: (BROKER) <-- PINGREQ
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:123: Trace: "[Elapsed]: 1000"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:381: Trace: "(BROKER) --> PINGRESP"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:123: Trace: "[Elapsed]: 1000"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:381: Trace: "(BROKER) --> PUBLISH"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:123: Trace: "[Elapsed]: 1000"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:381: Trace: "(BROKER) --> PUBLISH"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:123: Trace: "[Elapsed]: 1000"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:381: Trace: "(BROKER) --> PUBLISH"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:123: Trace: "[Elapsed]: 1000"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:371: Trace: "(CLIENT) --> PINGREQ"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:615: Trace: (CLIENT) <-- PUBLISH
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:631: Trace: "[Msg ID]: 0"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:615: Trace: (CLIENT) <-- PUBLISH
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:631: Trace: "[Msg ID]: 0"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:615: Trace: (CLIENT) <-- PUBLISH
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:631: Trace: "[Msg ID]: 0"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:789: Trace: (CLIENT) <-- PINGRESP
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:123: Trace: "[Elapsed]: 1000"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:381: Trace: "(BROKER) --> PUBLISH"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:123: Trace: "[Elapsed]: 1000"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:381: Trace: "(BROKER) --> PUBLISH"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:123: Trace: "[Elapsed]: 1000"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:381: Trace: "(BROKER) --> PUBLISH"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:123: Trace: "[Elapsed]: 1000"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:1491: Trace: [BROKER disconnected]
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:123: Trace: "[Elapsed]: 1000"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:371: Trace: "(CLIENT) --> CONNECT"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:441: Trace: (CLIENT) <-- CONNACK
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:615: Trace: (CLIENT) <-- PUBLISH
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:631: Trace: "[Msg ID]: 0"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:615: Trace: (CLIENT) <-- PUBLISH
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:631: Trace: "[Msg ID]: 0"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:615: Trace: (CLIENT) <-- PUBLISH
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:631: Trace: "[Msg ID]: 0"
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:513: Trace: (CLIENT) <-- DISCONNECT
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:1326: Trace: [Term]
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:1334: Trace: "Unverified data sent to client: 02 18 "
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:1334: Trace: "Unverified data sent to client: 02 18 "
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:1334: Trace: "Unverified data sent to client: 02 18 "
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:1337: Error: Assertion failed: state.m_sentToClient.empty()
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:199: Trace: (CLIENT) <-- DISCONNECT
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:199: Trace: (CLIENT) <-- DISCONNECT
/mnt/data/Work/P011-cc.mqttsn.libs/build.full.clang/gateway/test/../../../gateway/test/Session.th:199: Trace: (CLIENT) <-- DISCONNECT
```
You can see that at the end there are 3 unexpected "DISCONNECT" messages are attempted to be sent by the gateway to the client. If I read the code correctly the test16 is expected to test the behavior of the gateway when the client is in the sleep mode, i.e. the gateway is expected to accumulate all the published messages from the broker and then send them to the client when the latter reconnects. Looks like the proposed update has other previously not encountered side effects. More analysis is required.

As I mentioned in the relevant #12 issue, I'm on the limited capacity at this moment and probably won't be able to look at this issue in depth until end of July.

**Pull request merged**
